---
title: "Lab 1"
author: "Jamil Ahmed"
date: "2024-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.show='asis')
```

#Task 1
getwd()


ddt = read.csv("DDT.csv")

# First six lines
head(ddt)

#What class is the object ddt? (data frame)
class(ddt)

#what are the variables in the data frame? (qualitative variables)
names(ddt)

# Summarize the variables (What are the quantitative  variables)
summary(ddt)

# Manual entry
x=scan()


#Use the c "combine" operator to make vectors
y=c(1,2,3,4,5)


# manipulate the data frame
#Find the fish with weight more than 800gms
with(ddt, ddt[WEIGHT>800,])

#place the output in an object
b800=with(ddt, ddt[WEIGHT>800,])

#Summarize it
summary(b800)

# Use combination boolean expressions to subset
with(ddt, ddt[WEIGHT>800 & SPECIES=="LMBASS",])

#Subset the ddt data set so that we see only those observations where the RIVER is SCM
#and DDT bigger than 4.0
with(ddt, ddt[RIVER == "SCM" & DDT>4,])

#ordering data frames
with(ddt,ddt[order(WEIGHT),])


#More complex orderings
with(ddt,ddt[order(SPECIES,WEIGHT),])

with(ddt,ddt[order(SPECIES,DDT),])




#Using dplyr
library(dplyr)
library(ggplot2)
# notice how the infix %>% operator works ( the pipe )

ddt %>% filter(WEIGHT > 200, LENGTH > 30, DDT < 300) %>% mutate(AREA = LENGTH*WEIGHT) %>% ggplot(aes(x=AREA,y=DDT,fill=RIVER)) + geom_boxplot() + ggtitle("How to use dplyr and ggplot")


## Making vectors
v=1:10
v
2*v
2*v^2
sqrt(v)

#make  matrix
#nr=nu. of rows, byrow=TRUE, fill by row
mat=matrix(1:10,nr=5,nc=2,byrow=TRUE)
mat

#Adding names to columns and rows
#rep = repeat, repeat "r" 5 times
colnames(mat)=c("c1","c2")
rownames(mat)=paste(rep("r",5),1:5,sep="")

#entering the name of the object releases its contents
mat


#Use tables to summarize and plot categorical variables
sp=with(ddt,table(SPECIES))
sp
barplot(sp)
pie(sp,col=1:4)


#2-D tables
spriv=with(ddt,table(SPECIES,RIVER))
spriv
barplot(spriv)

#Add some options to make the graph more readable
barplot(spriv,beside=TRUE,col=1:3)

#2-D tables with reversing the variables
rivsp=with(ddt,table(RIVER,SPECIES))
rivsp

#Row and column sums
rowSums(rivsp)
colSums(rivsp)

#Proportion of the column totals
rivsp/colSums(rivsp)

#
barplot(rivsp,col=rainbow(4))

#Embellish the graphic using colors and a legend
barplot(rivsp,beside=TRUE,col=rainbow(4))
with(ddt,legend(1,80, leg=levels(RIVER),bty="n",fill=rainbow(4),cex=0.8))

#scatter plots
with(ddt,plot(WEIGHT~LENGTH))

#Use the data option
plot(WEIGHT~LENGTH,data=ddt)

#embellish the plot with species using color using 'ifelse(test,yes,no)'
fishcol=with(ddt,ifelse(SPECIES=="CCATFISH","Red",
                        ifelse(SPECIES=="SMBUFFALO","Blue","Green")))

#River col
rivcol=with(ddt, ifelse(RIVER=="FCM","Red",
                        ifelse(RIVER=="LCM","Blue",
                               ifelse(RIVER=="SCM","Green","Black"))))






# data.table

library(data.table)

#Q.1 Find the mean length of fish in the ddt data frame!
mean_fish_length <- mean(ddt$LENGTH)
cat("Mean length of fish:", mean_fish_length, "\n")
#42.8125

#Q.2 What is the standard deviation of the weight of fish
#in the ddt data frame?
sd(ddt$WEIGHT)
#376.5461



#Q.3 0 (titles are not on the correct axis)

#Q.4
v <- 1:20
result <- v/20
last_value <- tail(result, 1)

#task 5
#table of rivers
riv=with(ddt,table(RIVER))
riv

#color-coded barplot of rivers
barplot(riv,beside=TRUE,col=1:4)

#river crossed species table
rivsp=with(ddt,table(RIVER,SPECIES))
rivsp

#river crossed species barplot (now with color!)
barplot(rivsp,col=rainbow(4))

#task 6
#pie chart of SPECIES
pie(sp,col=rainbow(3))

#pie chart of RIVERS
pie(riv,col=1:4)

#task 7
with(ddt,boxplot(DDT,ylab="DDT",col="Red",notch=TRUE))
with(ddt,boxplot(WEIGHT,ylab="WEIGHT",col="blue",notch=TRUE))
with(ddt,boxplot(LENGTH,ylab="LENGTH",col="green",notch=TRUE))

#task8
#Make a coplot of LENGTH Vs WEIGHT given RIVER
coplot(WEIGHT~LENGTH|RIVER,data=ddt,col=fishcol)
#Make a coplot of DDT Vs WEIGHT given SPECIES
coplot(DDT~WEIGHT|SPECIES,data=ddt,col=fishcol)
#Task 9
#boxplot
ddt %>% ggplot(aes(x=SPECIES,y=WEIGHT,fill=RIVER)) + geom_boxplot() + ggtitle("Jamil Ahmed")

#violin plot
ddt %>% ggplot(aes(x=RIVER,y=LENGTH,fill=SPECIES)) + geom_violin() + ggtitle("Jamil Ahmed")


#scatter plot
ddt %>% ggplot(aes(x=WEIGHT,y=LENGTH,fill=SPECIES,col=SPECIES)) + geom_point() + ggtitle("Jamil Ahmed")



